### ISSUE TITLE
Fatal Error : displayTicket() must be an instance of Scrappers\void

### ISSUE THREAD

**Issue by atfera** [esgi-iw2-collaboratif-g6/scrapers#8]
I have a PHP Fatal Error when running the application: 

`PHP Fatal error:  Uncaught TypeError: Return value of Scrapers\ScraperManager::displayTicket() must be an instance of Scrapers\void, none returned in /home/atferhat/workspace/scrapers/src/ScraperManager.php:95
Stack trace:
#0 /home/atferhat/workspace/scrapers/src/ScraperManager.php(41): Scrapers\ScraperManager->displayTicket(Array)
#1 /home/atferhat/workspace/scrapers/index.php(8): Scrapers\ScraperManager->scrap()
#2 {main}
  thrown in /home/atferhat/workspace/scrapers/src/ScraperManager.php on line 95`

The bug can be solved if I remove the return type void from displayTicket().

**To Reproduce**

1. Use Bash on Windows
2. install php7.0
3. `php -f index.php`

**Comment by ivanPrunier** [comment]
You should upgrade your PHP version to 7.1.
